#!/bin/bash
#
# Script para atualizar o sistema e instalar programas após a instalação do Ubuntu e derivados.#
#
# Autor: Willian Alves da Silva
# E-mail: willrocknroll@gmail.com
#
#################################################################################################
#
# Atualizando o sistema #
#
echo "Atualizando o sistema..."

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get autoclean -y
sudo apt-get autoremove -y

#
# Instalando programas
#
echo "Instalando programas..."

echo "Instalando Putty"
sudo add-apt-repository universe
sudo apt-get update
sudo apt-get install putty -y

echo "Instalando Google Chrome"
sudo apt-get install google-chrome-stable -y

echo "Instalando Virt-manager"
sudo apt-get install qemu-kvm qemu virt-manager virt-viewer libvirt-bin

